version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: pgvector_db
    environment:
      POSTGRES_USER: weiwei
      POSTGRES_PASSWORD: weiwei
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .  # 使用當前目錄作為構建上下文
      dockerfile_inline: |  # 內聯 Dockerfile 內容
        FROM python:3.8
        WORKDIR /app

        # 更新 Poetry 路徑
        ENV PATH="${PATH}:/root/.local/bin"

        # 複製剩餘的專案代碼
        COPY . /app/

        RUN apt-get update -y
        RUN apt-get install -y bash
        RUN apt-get install python3-pip -y
        RUN pip install --upgrade pip setuptools wheel
        RUN pip install torch torchvision torchaudio
        RUN pip install -r requirements.txt

        # 開放 API 端口，這裡假設使用 FastAPI 來提供服務
        EXPOSE 8080

        CMD ["/bin/bash"]
    container_name: rag_app
    stdin_open: true
    tty: true
    depends_on:
      - db  # 保留對 db 的依賴
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: stock_db
      DB_USER: weiwei
      DB_PASSWORD: weiwei
    ports:
      - "8080:8080"  # 映射 8080 端口，與 EXPOSE 一致
    volumes:
      - ./app_data:/app  # 保留應用程式卷
    restart: unless-stopped

volumes:
  db_data:
