name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Pre-Commit
        run: pip install pre-commit
      - name: Run Pre-Commit Hooks
        uses: pre-commit/action@v3.0.0
  docker:
    name: Build Docker-Compose
    runs-on: ubuntu-latest
    needs: [pre-commit]  # 只有 pre-commit 和測試通過後才執行
    if: contains(github.event.head_commit.modified, 'docker-compose.yaml')  # 只有 Dockerfile 改變才執行
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker-Compose image
        run: docker-compose -f docker-compose.yaml up -d --build
      - name: Wait for services to be ready
        run: |
          sleep 10  # Adjust based on how long your services take to start
          docker-compose -f docker-compose.yaml ps
      - name: Stop Docker Compose services
        if: always()  # Run even if previous steps fail
        run: |
          docker-compose -f docker-compose.yaml down --volumes
